DROP DATABASE IF EXISTS example;
CREATE DATABASE IF NOT EXISTS example;

DROP DATABASE IF EXISTS sample;
CREATE DATABASE IF NOT EXISTS sample;

USE example;

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
	k INT,
	name VARCHAR(255)
);

INSERT INTO users VALUES
  (1,'Пользователь');
